### ISSUE TITLE
Remove vizceral project?

### ISSUE THREAD

**Issue by kikiya** [lightbend/Pi-Akka-Cluster#117]
Should we remove the vizceral project since it's no longer supported by telemetry team and also I believe deprecated by netflix as well? @eloots

**Comment by eloots** [comment]
@kikiya
👍 
Indeed! Submit a PR for it?

**Comment by agolubev** [comment]
does this mean just removing exercise_016_es_vizceral folder and corresponding project from build.sbt?

**Comment by kikiya** [comment]
yes, and I'll renumber the activities then submit the PR @agolubev

**Comment by agolubev** [comment]
Ok

**Comment by eloots** [comment]
Implemented as part of #119
