### ISSUE TITLE
Unused variable

### ISSUE THREAD

**Issue by eloots** [lightbend/Pi-Akka-Cluster#155]
(Just an example to illustrate the point I made in the review of PR #151)

As reported by the linter, variable `serverSource` is never used.

https://github.com/lightbend/Pi-Akka-Cluster/blob/26b4a519ffd8211e842f28e8aff97731efc48ce8/exercise_102_display_cluster_sharding/src/main/scala/com/lightbend/akka_oled/Main.scala#L69

**Comment by agolubev** [comment]
Addressed this in  PR #151

**Comment by eloots** [comment]
Thanks - Closing
