### ISSUE TITLE
Akka-pi-OS-install-instructions.md dont seem to work

### ISSUE THREAD

**Issue by nolangrace** [lightbend/Pi-Akka-Cluster#74]
Pi-Akka-Cluster/Akka-Pi-OS-install-instructions.md dont seem to work

flashing that image to the SD gets me stuck with this screen on the rasberry pi

![image](https://user-images.githubusercontent.com/1775305/49741883-03c1f100-fc5d-11e8-94f7-474fb852e9f6.png)

**Comment by eloots** [comment]
@nolangrace Seems you connected an external screen via the RPi HDMI connector. Note that, after you flash the card and boot from it the first time, the Pi goes through a number of steps such as resizing the file system and installing a number of packages (such as `tmux`). For the latter, it needs access to the Internet. Make sure that your Pi is connected to [most probably your home network]. The easiest way to do this is by using a properly configured travel router that connects to your home network via Wifi. See instructions near the bottom of the main README file.

**Comment by eloots** [comment]
@nolangrace Closing as no feedback was received on last post. I assume the issue has been solved in the mean time.
