### ISSUE TITLE
Add new exercise on 'Down All' Split brain resolver strategy

### ISSUE THREAD

**Issue by eloots** [lightbend/Pi-Akka-Cluster#89]
Recently, a new Akka Cluster Split Brain Resolver strategy, "Down all" was added. There should be an exercise to demo/try it.

**Comment by kikiya** [comment]
this one might be tricky to simulate. i have a feeling it will be good that we have physical nodes. 

https://developer.lightbend.com/docs/akka-commercial-addons/current/split-brain-resolver.html

**Comment by eloots** [comment]
Implemented as part of #97
