### ISSUE TITLE
Use Artery TCP

### ISSUE THREAD

**Issue by patriknw** [lightbend/Pi-Akka-Cluster#9]
If you are not using it already I'd recommend that you switch to Artery TCP that is new in Akka 2.5.11. It would be some additional indirect testing of the transport that will probably become the future (in 2.6) default. Thanks

See config in https://doc.akka.io/docs/akka/current/remoting-artery.html

**Comment by eloots** [comment]
Just read the docs on that topic. It requires a 64bit JVM. Not installed on the Pi’s, but it is available (from Oracle). Will move to a 64-bit JVM and give Artery TCP a try.

Will keep you posted.

**Comment by eloots** [comment]
Oops… Won’t work as the OS is 32-bit…

**Comment by eloots** [comment]
A 64-bit version of the OS we’re using is in the works: https://github.com/DieterReuter/image-builder-rpi64/releases/tag/v20180211-133408

To be investigated

**Comment by eloots** [comment]
I see it now. Misread Aeron as Artery.

**Comment by patriknw** [comment]
yeah, that is easy to do, something A...

**Comment by eloots** [comment]
Implemented as part of #18
